[package]
name = "rust-code-snippet"
version = "0.1.0"
authors = ["mahdi <mahdi.robatipoor@gmail.com>"]
edition = "2018"

[dependencies]
ferris-says = "0.1.1"
notifica = "1.0.2"
lazy_static = "1.3.0"
graceful = "0.1.1"
rand = "0.6.5"
